### ISSUE TITLE
Cannot specify config-file

### ISSUE THREAD

**Issue by DeutscheGabanna** [natelandau/jdfile#9]
```
PS C:\Users\Paul> filemanager.exe --config-file D:\filemanager.toml
ERROR    | No files were specified
PS C:\Users\Paul> filemanager.exe --config-file "D:\filemanager.toml"
ERROR    | No files were specified
```
Done on powershell windows. Also, how do you understand this fragment with `~` from the `README.md` if running `filemanager` on Windows?
> filemanager will clean filenames without needing a configuration file. To organize files into folders, a valid [toml](https://toml.io/en/) configuration file is required at ~/.filemanager/filemanager.toml

**Comment by DeutscheGabanna** [comment]
The `.toml` file in question:
```
ignored_files = ['.DS_Store', '.bashrc', 'something_not_to_rename'] # If cleaning an entire directory, files in this list will be skipped
match_case = ["OKR", "OKRs", "KPI", "KPIs"]  # Force the casing of certain words. Great for acronyms or proper nouns.

[projects]                      # Define any number of different projects

[projects.jdc]            # A Johnny Decimal project
name = "jdc"                   # (Required)  Name of this project (used as a command line option --organize=test)
path = "d:/jdc"        # (Required) Path to the folder containing the Johnny Decimal project
stopwords = ["stopword", "stopword"]   # Optional list of project specific stopwords
```

**Comment by natelandau** [comment]
The tilde (`~`) is shorthand for a user's home directory.  If a file is located at `/Users/username/file.txt`, using the tilde allows one to write `~/file.txt`

I just double-checked that specifying a config file works under MacOS and Linux. Unfortunately, I have no ability to test this script in a Windows powershell environment. I would welcome any pull requests that fixed the issue you're having.

Wish I had a better answer.

**Comment by natelandau** [comment]
@DeutscheGabanna I just made a change which may fix the issue you are encountering specifying the configuration file.  As noted, I can not test this on Windows but give `v0.4.6` a shot.
